# Generated by Django 4.2.7 on 2026-04-19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('description', tinymce.models.HTMLField(blank=True, default='', verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, default='', max_length=500, verbose_name='Краткое описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/', verbose_name='Логотип')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Meta Keywords')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район Москвы')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('working_hours', models.CharField(default='Круглосуточно', max_length=100, verbose_name='Часы работы')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за км')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Минимальная стоимость')),
                ('has_parking', models.BooleanField(default=True, verbose_name='Парковка')),
                ('has_toilet', models.BooleanField(default=True, verbose_name='Туалет')),
                ('has_available_environment', models.BooleanField(default=True, verbose_name='Доступная среда')),
                ('has_cafe', models.BooleanField(default=True, verbose_name='Кафе')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Wi-Fi')),
                ('has_cash_machine', models.BooleanField(default=True, verbose_name='Банкомат')),
                ('has_cargo', models.BooleanField(default=True, verbose_name='Грузовое такси')),
                ('has_children_seat', models.BooleanField(default=True, verbose_name='Детское кресло')),
                ('has_animal_transport', models.BooleanField(default=True, verbose_name='Перевозка животных')),
                ('has_minivan', models.BooleanField(default=True, verbose_name='Минивэн')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
