# Generated by Django 4.2.7 on 2026-05-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_faq_alter_product_video_source_like'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='product_categories',
            field=models.ManyToManyField(blank=True, related_name='shops', to='catalog.category', verbose_name='Категории товаров для показа'),
        ),
    ]
