# Generated by Django 4.2.7 on 2026-04-14 20:37

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='XML ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень')),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None, verbose_name='Путь')),
                ('meta_title', models.CharField(blank=True, max_length=300, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во товаров')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='XML ID')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Штрихкод')),
                ('url', models.URLField(max_length=500, verbose_name='URL товара')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('description_raw', models.TextField(blank=True, default='', verbose_name='Исходное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(default='RUR', max_length=3, verbose_name='Валюта')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('pickup_available', models.BooleanField(default=True, verbose_name='Самовывоз')),
                ('delivery_available', models.BooleanField(default=True, verbose_name='Доставка')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), default=list, size=None, verbose_name='Изображения')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Бренд')),
                ('vendor', models.CharField(blank=True, max_length=200, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Страна происхождения')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вес (кг)')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='Габариты')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Отзывы')),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True, verbose_name='Поиск')),
                ('meta_title', models.CharField(blank=True, max_length=300, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('categories', models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-price'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['params'], name='catalog_pro_params_4982b7_gin'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_pro_search__6e8905_gin'), models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'), models.Index(fields=['price'], name='catalog_pro_price_2d2a4c_idx'), models.Index(fields=['brand'], name='catalog_pro_brand_f6911e_idx'), models.Index(fields=['-likes_count'], name='catalog_pro_likes_c_16d084_idx'), models.Index(fields=['-views_count'], name='catalog_pro_views_c_5941c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'level'], name='catalog_cat_parent__0ebb1f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
    ]
