# Generated by Django 4.2.7 on 2026-05-02 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.TextField(blank=True, default='', verbose_name='FAQ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_source',
            field=models.TextField(blank=True, default='', verbose_name='Источник видео'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'unique_together': {('product', 'ip_address')},
            },
        ),
    ]
