# Generated by Django 4.2.7 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.TextField(blank=True, default='[]', verbose_name='Изображения'),
        ),
    ]
